import { useState, useEffect } from "react";
import supabase from "./supabase";
import jsPDF from 'jspdf';
import 'jspdf-autotable';

function uid() { return Math.random().toString(36).slice(2, 9).toUpperCase(); }
function generateOTP() { return Math.floor(100000 + Math.random() * 900000).toString(); }

function downloadPDF(rx, doctor, patient) {
  const doc = new jsPDF();
  doc.setFontSize(20);
  doc.setTextColor(26, 107, 138);
  doc.text("MediConnect", 105, 20, { align: "center" });
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text("Prescription", 105, 28, { align: "center" });
  doc.setDrawColor(26, 107, 138);
  doc.line(20, 32, 190, 32);
  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.text(`Doctor: Dr. ${doctor?.name || "N/A"}`, 20, 42);
  doc.text(`Specialization: ${doctor?.specialization || "N/A"}`, 20, 50);
  doc.text(`Date: ${rx.date}`, 150, 42);
  doc.setDrawColor(200);
  doc.line(20, 56, 190, 56);
  doc.text(`Patient: ${patient?.name || "N/A"}`, 20, 64);
  doc.text(`ID: ${patient?.unique_id || "N/A"}`, 20, 72);
  doc.text(`Age: ${patient?.age || "N/A"}   Blood Group: ${patient?.blood_group || "N/A"}`, 20, 80);
  doc.line(20, 86, 190, 86);
  doc.setFontSize(12);
  doc.setTextColor(26, 107, 138);
  doc.text(`Diagnosis: ${rx.diagnosis}`, 20, 96);
  const medicines = rx.prescription_medicines || [];
  if (medicines.length > 0) {
    doc.autoTable({
      startY: 104,
      head: [["Medicine", "Dosage", "Frequency", "Duration"]],
      body: medicines.map(m => [m.medicine_name, m.dosage || "", m.frequency || "", m.duration || ""]),
      headStyles: { fillColor: [26, 107, 138] },
      margin: { left: 20, right: 20 },
    });
  }
  if (rx.notes) {
    const finalY = doc.lastAutoTable?.finalY || 120;
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Notes: ${rx.notes}`, 20, finalY + 10);
  }
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Generated by MediConnect — India's Complete Healthcare Platform", 105, 285, { align: "center" });
  doc.save(`Prescription-${rx.diagnosis}-${rx.date}.pdf`);
}

const C = {
  bg: "#F5F7FA", card: "#FFFFFF", primary: "#1A6B8A", primaryLight: "#E8F4F8",
  accent: "#2ECC9B", accentLight: "#E8FAF4", danger: "#E74C3C", dangerLight: "#FDECEA",
  warning: "#F39C12", warningLight: "#FEF9E7", purple: "#9B59B6", purpleLight: "#F3E8FF",
  text: "#1A2B3C", muted: "#7A8FA6", border: "#E2EAF0",
  shadow: "0 2px 12px rgba(26,107,138,0.08)",
};

const s = {
  page: { minHeight: "100vh", background: C.bg, fontFamily: "'Palatino Linotype', Georgia, serif", color: C.text },
  card: { background: C.card, borderRadius: 16, boxShadow: C.shadow, border: `1px solid ${C.border}` },
  input: { width: "100%", boxSizing: "border-box", border: `1.5px solid ${C.border}`, borderRadius: 10, padding: "10px 14px", fontSize: 14, fontFamily: "inherit", color: C.text, background: "#fff", outline: "none" },
  label: { fontSize: 11, fontWeight: 700, color: C.muted, letterSpacing: 1, textTransform: "uppercase", display: "block", marginBottom: 6 },
  btn: (v = "primary") => ({ padding: "10px 20px", borderRadius: 10, border: "none", cursor: "pointer", fontFamily: "inherit", fontWeight: 700, fontSize: 14, background: v === "primary" ? C.primary : v === "accent" ? C.accent : v === "danger" ? C.danger : v === "warning" ? C.warning : v === "purple" ? C.purple : "#EDF2F7", color: v === "ghost" ? C.muted : "#fff" }),
  badge: (color) => ({ display: "inline-block", borderRadius: 20, padding: "3px 10px", fontSize: 11, fontWeight: 700, background: color + "22", color, border: `1px solid ${color}44` }),
};

const ROLES = [
  { id: "patient", icon: "🧑", label: "Patient", color: C.accent, desc: "View your prescriptions & health records" },
  { id: "doctor", icon: "👨‍⚕️", label: "Doctor", color: C.primary, desc: "Manage patients & write prescriptions" },
  { id: "medical_store", icon: "🏪", label: "Medical Store", color: C.warning, desc: "Dispense medicines & manage orders" },
  { id: "test_lab", icon: "🔬", label: "Test Lab", color: C.purple, desc: "Manage test bookings & reports" },
];

export default function App() {
  const [currentUser, setCurrentUser] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (session?.user) fetchUserProfile(session.user.id);
      else setLoading(false);
    });
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      if (session?.user) fetchUserProfile(session.user.id);
      else { setCurrentUser(null); setLoading(false); }
    });
    return () => subscription.unsubscribe();
  }, []);

  async function fetchUserProfile(userId) {
    const { data } = await supabase.from("users").select("*").eq("id", userId).single();
    if (data) setCurrentUser(data);
    setLoading(false);
  }

  const logout = async () => { await supabase.auth.signOut(); };

  if (loading) return (
    <div style={{ ...s.page, display: "flex", alignItems: "center", justifyContent: "center" }}>
      <div style={{ textAlign: "center" }}>
        <div style={{ fontSize: 48, marginBottom: 16 }}>🏥</div>
        <p style={{ color: C.muted }}>Loading MediConnect...</p>
      </div>
    </div>
  );

  if (!currentUser) return <AuthScreen onLogin={setCurrentUser} />;
  if (currentUser.role === "admin") return <AdminDashboard user={currentUser} onLogout={logout} />;
  if (currentUser.role === "doctor") return <DoctorDashboard user={currentUser} onLogout={logout} />;
  if (currentUser.role === "patient") return <PatientDashboard user={currentUser} onLogout={logout} />;
  if (currentUser.role === "medical_store") return <MedicalStoreDashboard user={currentUser} onLogout={logout} />;
  if (currentUser.role === "test_lab") return <TestLabDashboard user={currentUser} onLogout={logout} />;
}

// ─── AUTH SCREEN ──────────────────────────────────────────────────────────────
function AuthScreen({ onLogin }) {
  const [screen, setScreen] = useState("home"); // home | login | register
  const [selectedRole, setSelectedRole] = useState(null);
  const [form, setForm] = useState({ name: "", email: "", password: "", specialization: "", age: "", bloodGroup: "", storeName: "", address: "", licenseNo: "" });
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleLogin() {
    setLoading(true); setError("");
    try {
      const { data, error } = await supabase.auth.signInWithPassword({ email: form.email, password: form.password });
      if (error) throw error;
      const { data: profile } = await supabase.from("users").select("*").eq("id", data.user.id).single();
      if (!profile) throw new Error("Profile not found.");
      if (!profile.approved && profile.role !== "admin") throw new Error("Account pending admin approval.");
      onLogin(profile);
    } catch (err) { setError(err.message); }
    setLoading(false);
  }

  async function handleRegister() {
    if (!form.name || !form.email || !form.password) return setError("Please fill all required fields.");
    setLoading(true); setError("");
    try {
      const { data, error } = await supabase.auth.signUp({ email: form.email, password: form.password });
      if (error) throw error;

      let uniqueId = `PAT-${uid()}`;
      if (selectedRole === "doctor") uniqueId = `DOC-${uid()}`;
      if (selectedRole === "medical_store") uniqueId = `MED-${uid()}`;
      if (selectedRole === "test_lab") uniqueId = `LAB-${uid()}`;

      const newProfile = {
        id: data.user.id, name: form.name, email: form.email,
        role: selectedRole, unique_id: uniqueId, approved: false,
        password_hash: "supabase-auth",
        specialization: form.specialization || null,
        age: form.age ? parseInt(form.age) : null,
        blood_group: form.bloodGroup || null,
        store_name: form.storeName || null,
        address: form.address || null,
        license_no: form.licenseNo || null,
      };

      const { error: profileError } = await supabase.from("users").insert(newProfile);
      if (profileError) throw profileError;
      setScreen("home");
      setSelectedRole(null);
      setForm({ name: "", email: "", password: "", specialization: "", age: "", bloodGroup: "", storeName: "", address: "", licenseNo: "" });
      alert("Registration successful! Please wait for admin approval.");
    } catch (err) { setError(err.message); }
    setLoading(false);
  }

  // HOME SCREEN — Role Selection
  if (screen === "home") return (
    <div style={{ ...s.page, display: "flex", alignItems: "center", justifyContent: "center", padding: 20 }}>
      <div style={{ width: "100%", maxWidth: 480 }}>
        <div style={{ textAlign: "center", marginBottom: 36 }}>
          <div style={{ fontSize: 56, marginBottom: 12 }}>🏥</div>
          <h1 style={{ margin: 0, fontSize: 32, color: C.primary, letterSpacing: -0.5 }}>MediConnect</h1>
          <p style={{ margin: "6px 0 0", color: C.muted, fontSize: 14 }}>India's Complete Healthcare Platform</p>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14, marginBottom: 20 }}>
          {ROLES.map(role => (
            <button key={role.id} onClick={() => { setSelectedRole(role.id); setScreen("login"); setError(""); }} style={{
              ...s.card, padding: 20, border: `2px solid ${role.color}33`,
              cursor: "pointer", textAlign: "center", background: "#fff",
              transition: "all 0.2s", fontFamily: "inherit",
            }}>
              <div style={{ fontSize: 36, marginBottom: 8 }}>{role.icon}</div>
              <div style={{ fontWeight: 700, fontSize: 15, color: role.color, marginBottom: 4 }}>{role.label}</div>
              <div style={{ fontSize: 11, color: C.muted, lineHeight: 1.4 }}>{role.desc}</div>
            </button>
          ))}
        </div>

        <div style={{ textAlign: "center", padding: "14px", background: C.primaryLight, borderRadius: 12 }}>
          <span style={{ color: C.muted, fontSize: 13 }}>Admin? </span>
          <button onClick={() => { setSelectedRole("admin"); setScreen("login"); setError(""); }} style={{ background: "none", border: "none", color: C.primary, fontWeight: 700, cursor: "pointer", fontSize: 13, fontFamily: "inherit" }}>Login here →</button>
        </div>
      </div>
    </div>
  );

  const roleInfo = ROLES.find(r => r.id === selectedRole) || { icon: "🔐", label: "Admin", color: C.danger };

  // LOGIN / REGISTER SCREEN
  return (
    <div style={{ ...s.page, display: "flex", alignItems: "center", justifyContent: "center", padding: 20 }}>
      <div style={{ width: "100%", maxWidth: 420 }}>
        <button onClick={() => { setScreen("home"); setSelectedRole(null); setError(""); }} style={{ background: "none", border: "none", color: C.muted, cursor: "pointer", fontSize: 14, marginBottom: 16, fontFamily: "inherit", display: "flex", alignItems: "center", gap: 6 }}>← Back</button>

        <div style={{ textAlign: "center", marginBottom: 24 }}>
          <div style={{ fontSize: 40, marginBottom: 6 }}>{roleInfo.icon}</div>
          <h2 style={{ margin: 0, fontSize: 22, color: roleInfo.color }}>{roleInfo.label} Portal</h2>
          <p style={{ margin: "4px 0 0", color: C.muted, fontSize: 13 }}>MediConnect</p>
        </div>

        <div style={{ ...s.card, padding: 28 }}>
          {selectedRole !== "admin" && (
            <div style={{ display: "flex", background: C.bg, borderRadius: 10, padding: 4, marginBottom: 24 }}>
              {["login", "register"].map(t => (
                <button key={t} onClick={() => { setScreen(t === "login" ? "login" : "register"); setError(""); }} style={{ flex: 1, padding: "8px 0", borderRadius: 8, border: "none", fontFamily: "inherit", fontSize: 13, cursor: "pointer", background: screen === t ? C.card : "transparent", color: screen === t ? roleInfo.color : C.muted, fontWeight: screen === t ? 700 : 400 }}>{t === "login" ? "Login" : "Register"}</button>
              ))}
            </div>
          )}

          {screen === "register" && <Field label="Full Name" value={form.name} onChange={v => setForm(f => ({ ...f, name: v }))} placeholder="Your full name" />}
          <Field label="Email" value={form.email} onChange={v => setForm(f => ({ ...f, email: v }))} placeholder="email@example.com" type="email" />
          <Field label="Password" value={form.password} onChange={v => setForm(f => ({ ...f, password: v }))} placeholder="Password (min 6 chars)" type="password" />

          {screen === "register" && selectedRole === "doctor" && (
            <div style={{ marginBottom: 14 }}>
              <label style={s.label}>Specialization</label>
              <select value={form.specialization} onChange={e => setForm(f => ({ ...f, specialization: e.target.value }))} style={{ ...s.input, marginBottom: 0 }}>
                <option value="">Select Specialization</option>
                <option>Cardiologist</option>
                <option>General Physician</option>
                <option>Dermatologist</option>
                <option>Orthopedic</option>
                <option>Neurologist</option>
                <option>Gynecologist</option>
                <option>Pediatrician</option>
                <option>ENT Specialist</option>
                <option>Ophthalmologist</option>
                <option>Psychiatrist</option>
                <option>Urologist</option>
                <option>Oncologist</option>
                <option>Diabetologist</option>
                <option>Pulmonologist</option>
                <option>Gastroenterologist</option>
                <option>Rheumatologist</option>
                <option>Endocrinologist</option>
                <option>Nephrologist</option>
                <option>Hematologist</option>
                <option>Other</option>
              </select>
            </div>
          )}
          {screen === "register" && selectedRole === "patient" && (
            <div style={{ display: "flex", gap: 10 }}>
              <div style={{ flex: 1 }}><Field label="Age" value={form.age} onChange={v => setForm(f => ({ ...f, age: v }))} placeholder="25" type="number" /></div>
              <div style={{ flex: 1 }}><Field label="Blood Group" value={form.bloodGroup} onChange={v => setForm(f => ({ ...f, bloodGroup: v }))} placeholder="O+" /></div>
            </div>
          )}
          {screen === "register" && (selectedRole === "medical_store" || selectedRole === "test_lab") && (
            <>
              <Field label={selectedRole === "medical_store" ? "Store Name" : "Lab Name"} value={form.storeName} onChange={v => setForm(f => ({ ...f, storeName: v }))} placeholder={selectedRole === "medical_store" ? "e.g. City Pharmacy" : "e.g. HealthPath Labs"} />
              <Field label="Address" value={form.address} onChange={v => setForm(f => ({ ...f, address: v }))} placeholder="Full address" />
              <Field label="License Number" value={form.licenseNo} onChange={v => setForm(f => ({ ...f, licenseNo: v }))} placeholder="License/Registration No." />
            </>
          )}

          {error && <p style={{ color: C.danger, fontSize: 13, marginBottom: 14, padding: "8px 12px", background: C.dangerLight, borderRadius: 8 }}>{error}</p>}

          <button onClick={screen === "register" ? handleRegister : handleLogin} disabled={loading}
            style={{ ...s.btn("primary"), width: "100%", padding: "12px", opacity: loading ? 0.7 : 1, background: roleInfo.color }}>
            {loading ? "Please wait..." : screen === "register" ? "Register" : "Login"}
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── ADMIN DASHBOARD ──────────────────────────────────────────────────────────
function AdminDashboard({ user, onLogout }) {
  const [tab, setTab] = useState("overview");
  const [users, setUsers] = useState([]);
  const [prescriptions, setPrescriptions] = useState([]);

  useEffect(() => { fetchData(); }, []);

  async function fetchData() {
    const { data: u } = await supabase.from("users").select("*").order("created_at", { ascending: false });
    const { data: rx } = await supabase.from("prescriptions").select("*");
    setUsers(u || []); setPrescriptions(rx || []);
  }

  const doctors = users.filter(u => u.role === "doctor");
  const patients = users.filter(u => u.role === "patient");
  const stores = users.filter(u => u.role === "medical_store");
  const labs = users.filter(u => u.role === "test_lab");
  const pending = users.filter(u => u.role !== "admin" && !u.approved);

  async function approve(id) { await supabase.from("users").update({ approved: true }).eq("id", id); fetchData(); }
  async function reject(id) { await supabase.from("users").delete().eq("id", id); fetchData(); }

  return (
    <Layout user={user} onLogout={onLogout} role="admin"
      tabs={[["overview", "📊 Overview"], ["doctors", "👨‍⚕️ Doctors"], ["patients", "🧑 Patients"], ["stores", "🏪 Stores"], ["labs", "🔬 Labs"], ["pending", `⏳ Pending${pending.length ? ` (${pending.length})` : ""}`]]}
      activeTab={tab} onTabChange={setTab}
    >
      {tab === "overview" && (
        <div>
          <h2 style={headingStyle}>Dashboard Overview</h2>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 14, marginBottom: 28 }}>
            <StatCard icon="👨‍⚕️" label="Doctors" value={doctors.length} color={C.primary} />
            <StatCard icon="🧑" label="Patients" value={patients.length} color={C.accent} />
            <StatCard icon="🏪" label="Med Stores" value={stores.length} color={C.warning} />
            <StatCard icon="🔬" label="Test Labs" value={labs.length} color={C.purple} />
            <StatCard icon="📋" label="Prescriptions" value={prescriptions.length} color="#9B59B6" />
            <StatCard icon="⏳" label="Pending" value={pending.length} color={C.danger} />
          </div>
          {pending.length > 0 && <><h3 style={{ color: C.danger, fontSize: 15, marginBottom: 12 }}>⚠️ Pending Approvals</h3>{pending.map(u => <PendingCard key={u.id} user={u} onApprove={() => approve(u.id)} onReject={() => reject(u.id)} />)}</>}
          {pending.length === 0 && <Empty text="No pending approvals!" />}
        </div>
      )}
      {tab === "doctors" && <div><h2 style={headingStyle}>Registered Doctors</h2>{doctors.length === 0 ? <Empty text="No doctors yet." /> : doctors.map(d => <UserCard key={d.id} user={d} extra={d.specialization} onDelete={() => reject(d.id)} />)}</div>}
      {tab === "patients" && <div><h2 style={headingStyle}>Registered Patients</h2>{patients.length === 0 ? <Empty text="No patients yet." /> : patients.map(p => <UserCard key={p.id} user={p} extra={`Age ${p.age} • ${p.blood_group}`} onDelete={() => reject(p.id)} />)}</div>}
      {tab === "stores" && <div><h2 style={headingStyle}>Medical Stores</h2>{stores.length === 0 ? <Empty text="No stores yet." /> : stores.map(s => <UserCard key={s.id} user={s} extra={s.store_name || s.address} onDelete={() => reject(s.id)} />)}</div>}
      {tab === "labs" && <div><h2 style={headingStyle}>Test Labs</h2>{labs.length === 0 ? <Empty text="No labs yet." /> : labs.map(l => <UserCard key={l.id} user={l} extra={l.store_name || l.address} onDelete={() => reject(l.id)} />)}</div>}
      {tab === "pending" && <div><h2 style={headingStyle}>Pending Approvals</h2>{pending.length === 0 ? <Empty text="No pending approvals." /> : pending.map(u => <PendingCard key={u.id} user={u} onApprove={() => approve(u.id)} onReject={() => reject(u.id)} />)}</div>}
    </Layout>
  );
}

// ─── DOCTOR DASHBOARD ─────────────────────────────────────────────────────────
function DoctorDashboard({ user, onLogout }) {
  const [tab, setTab] = useState("find");
  const [searchId, setSearchId] = useState("");
  const [searchResult, setSearchResult] = useState(null);
  const [searchError, setSearchError] = useState("");
  const [otpSent, setOtpSent] = useState(false);
  const [otpCode, setOtpCode] = useState("");
  const [otpInput, setOtpInput] = useState("");
  const [otpError, setOtpError] = useState("");
  const [accessGranted, setAccessGranted] = useState(false);
  const [patientPrescriptions, setPatientPrescriptions] = useState([]);
  const [showRxForm, setShowRxForm] = useState(false);
  const [myPrescriptions, setMyPrescriptions] = useState([]);
  const [loading, setLoading] = useState(false);
  const [otpRequestId, setOtpRequestId] = useState(null);

  useEffect(() => { fetchMyPrescriptions(); }, []);

  async function fetchMyPrescriptions() {
    const { data } = await supabase.from("prescriptions").select(`*, prescription_medicines(*), patient:patient_id(name, unique_id, age, blood_group)`).eq("doctor_id", user.id).order("date", { ascending: false });
    setMyPrescriptions(data || []);
  }

  async function searchPatient() {
    setSearchError(""); setSearchResult(null); setOtpSent(false); setAccessGranted(false);
    const { data } = await supabase.from("users").select("*").eq("unique_id", searchId.trim().toUpperCase()).eq("role", "patient").eq("approved", true).single();
    if (data) setSearchResult(data);
    else setSearchError("No patient found with this ID.");
  }

  async function sendOTP() {
    setLoading(true);
    const otp = generateOTP();
    const expiresAt = new Date(Date.now() + 10 * 60 * 1000).toISOString();
    const { data: otpData } = await supabase.from("otp_requests").insert({
      doctor_id: user.id, patient_id: searchResult.id, otp_code: otp, expires_at: expiresAt,
    }).select().single();
    setOtpCode(otp);
    setOtpRequestId(otpData?.id);
    setOtpSent(true);
    setLoading(false);
  }

  async function verifyOTP() {
    const { data: otpData } = await supabase.from("otp_requests").select("*").eq("id", otpRequestId).single();
    if (otpData?.patient_approved) {
      setAccessGranted(true); setOtpError("");
      const { data } = await supabase.from("prescriptions").select(`*, prescription_medicines(*), doctor:doctor_id(name, specialization)`).eq("patient_id", searchResult.id).order("date", { ascending: false });
      setPatientPrescriptions(data || []);
    } else if (otpInput === otpCode) {
      setAccessGranted(true); setOtpError("");
      const { data } = await supabase.from("prescriptions").select(`*, prescription_medicines(*), doctor:doctor_id(name, specialization)`).eq("patient_id", searchResult.id).order("date", { ascending: false });
      setPatientPrescriptions(data || []);
    } else {
      setOtpError("Invalid OTP or patient hasn't approved yet.");
    }
  }

  async function savePrescription(rxData) {
    const { data: rx, error } = await supabase.from("prescriptions").insert({ diagnosis: rxData.diagnosis, notes: rxData.notes, doctor_id: user.id, patient_id: searchResult.id }).select().single();
    if (error) { alert("Error saving prescription!"); return; }
    await supabase.from("prescription_medicines").insert(rxData.medicines.map(m => ({ medicine_name: m.name, dosage: m.dosage, frequency: m.frequency, duration: m.duration, prescription_id: rx.id })));
    
    // Save vitals if provided
    if (rxData.vitals) {
      const v = rxData.vitals;
      const vitalsData = {
        patient_id: searchResult.id, doctor_id: user.id, prescription_id: rx.id,
        bp_systolic: v.bp_systolic ? parseInt(v.bp_systolic) : null,
        bp_diastolic: v.bp_diastolic ? parseInt(v.bp_diastolic) : null,
        sugar_fasting: v.sugar_fasting ? parseInt(v.sugar_fasting) : null,
        sugar_pp: v.sugar_pp ? parseInt(v.sugar_pp) : null,
        cholesterol: v.cholesterol ? parseInt(v.cholesterol) : null,
        weight: v.weight ? parseFloat(v.weight) : null,
        temperature: v.temperature ? parseFloat(v.temperature) : null,
      };
      await supabase.from("vitals").insert(vitalsData);
    }

    setShowRxForm(false); fetchMyPrescriptions();
    const { data } = await supabase.from("prescriptions").select(`*, prescription_medicines(*), doctor:doctor_id(name, specialization)`).eq("patient_id", searchResult.id).order("date", { ascending: false });
    setPatientPrescriptions(data || []);
    alert("Prescription saved!");
  }

  function resetSearch() {
    setSearchId(""); setSearchResult(null); setOtpSent(false);
    setOtpCode(""); setOtpInput(""); setOtpError("");
    setAccessGranted(false); setPatientPrescriptions([]);
    setShowRxForm(false); setOtpRequestId(null);
  }

  return (
    <Layout user={user} onLogout={onLogout} role="doctor"
      tabs={[["find", "🔍 Find Patient"], ["myprescriptions", "📋 My Prescriptions"]]}
      activeTab={tab} onTabChange={(t) => { setTab(t); resetSearch(); }} subtitle={user.specialization}
    >
      {tab === "find" && !showRxForm && (
        <div>
          <h2 style={headingStyle}>Find Patient</h2>
          {!searchResult && (
            <div style={{ ...s.card, padding: 20, marginBottom: 20 }}>
              <div style={{ fontWeight: 700, color: C.primary, marginBottom: 8 }}>Step 1: Enter Patient Unique ID</div>
              <div style={{ display: "flex", gap: 10 }}>
                <input value={searchId} onChange={e => setSearchId(e.target.value)} onKeyDown={e => e.key === "Enter" && searchPatient()} placeholder="e.g. PAT-ABC123" style={{ ...s.input, marginBottom: 0 }} />
                <button onClick={searchPatient} style={s.btn("primary")}>Search</button>
              </div>
              {searchError && <p style={{ color: C.danger, fontSize: 13, marginTop: 10 }}>{searchError}</p>}
            </div>
          )}
          {searchResult && !otpSent && (
            <div style={{ ...s.card, padding: 20, marginBottom: 20 }}>
              <div style={{ fontWeight: 700, color: C.primary, marginBottom: 12 }}>Step 2: Patient Found</div>
              <div style={{ padding: 16, background: C.accentLight, borderRadius: 12, marginBottom: 16 }}>
                <div style={{ fontWeight: 700, fontSize: 16 }}>{searchResult.name}</div>
                <div style={{ color: C.muted, fontSize: 13 }}>{searchResult.unique_id} • Age {searchResult.age} • {searchResult.blood_group}</div>
              </div>
              <div style={{ display: "flex", gap: 10 }}>
                <button onClick={resetSearch} style={{ ...s.btn("ghost"), flex: 1 }}>← Back</button>
                <button onClick={sendOTP} disabled={loading} style={{ ...s.btn("primary"), flex: 2 }}>{loading ? "Sending..." : "📲 Send Access Request to Patient"}</button>
              </div>
            </div>
          )}
          {searchResult && otpSent && !accessGranted && (
            <div style={{ ...s.card, padding: 20, marginBottom: 20 }}>
              <div style={{ fontWeight: 700, color: C.primary, marginBottom: 12 }}>Step 3: Waiting for Patient Approval</div>
              <div style={{ padding: 16, background: C.warningLight, borderRadius: 12, marginBottom: 16, border: `1px solid ${C.warning}44` }}>
                <div style={{ fontWeight: 700, color: C.warning, marginBottom: 4 }}>⏳ Request Sent!</div>
                <p style={{ color: C.muted, fontSize: 13, margin: 0 }}>Patient ke app mein OTP request gayi hai.</p>
              </div>
              <Field label="Patient ne OTP bataya? Enter karo:" value={otpInput} onChange={setOtpInput} placeholder="6-digit OTP" />
              {otpError && <p style={{ color: C.danger, fontSize: 13, marginBottom: 10 }}>{otpError}</p>}
              <div style={{ display: "flex", gap: 10 }}>
                <button onClick={resetSearch} style={{ ...s.btn("ghost"), flex: 1 }}>← Back</button>
                <button onClick={verifyOTP} style={{ ...s.btn("primary"), flex: 2 }}>✓ Verify & Get Access</button>
              </div>
            </div>
          )}
          {searchResult && accessGranted && (
            <div>
              <div style={{ ...s.card, padding: 16, marginBottom: 20, background: C.accentLight, border: `1px solid ${C.accent}44` }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  <div>
                    <div style={{ fontWeight: 700, fontSize: 16 }}>✅ Access Granted — {searchResult.name}</div>
                    <div style={{ color: C.muted, fontSize: 13 }}>{searchResult.unique_id} • Age {searchResult.age} • {searchResult.blood_group}</div>
                  </div>
                  <div style={{ display: "flex", gap: 8 }}>
                    <button onClick={() => setShowRxForm(true)} style={s.btn("primary")}>✍️ Write Rx</button>
                    <button onClick={resetSearch} style={s.btn("ghost")}>✕</button>
                  </div>
                </div>
              </div>
              <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 12 }}>All Prescriptions ({patientPrescriptions.length})</h3>
              {patientPrescriptions.length === 0 ? <Empty text="No prescriptions yet." /> :
                patientPrescriptions.map(rx => <RxCard key={rx.id} rx={rx} showDoctor doctor={rx.doctor} />)}
            </div>
          )}
        </div>
      )}
      {tab === "find" && showRxForm && <PrescriptionForm patient={searchResult} onSave={savePrescription} onCancel={() => setShowRxForm(false)} />}
      {tab === "myprescriptions" && (
        <div>
          <h2 style={headingStyle}>My Prescriptions</h2>
          {myPrescriptions.length === 0 ? <Empty text="No prescriptions yet." /> :
            myPrescriptions.map(rx => <RxCard key={rx.id} rx={rx} showPatient patient={rx.patient} />)}
        </div>
      )}
    </Layout>
  );
}

// ─── PATIENT DASHBOARD ────────────────────────────────────────────────────────
function PatientDashboard({ user, onLogout }) {
  const [tab, setTab] = useState("requests");
  const [prescriptions, setPrescriptions] = useState([]);
  const [pendingRequests, setPendingRequests] = useState([]);
  const [vitals, setVitals] = useState([]);
  const [doctors, setDoctors] = useState([]);
  const [searchSpec, setSearchSpec] = useState("");

  useEffect(() => {
    fetchPrescriptions();
    fetchPendingRequests();
    fetchVitals();
    fetchDoctors();
    const interval = setInterval(fetchPendingRequests, 10000);
    return () => clearInterval(interval);
  }, []);

  async function fetchDoctors() {
    const { data } = await supabase.from("users").select("*").eq("role", "doctor").eq("approved", true).order("name");
    setDoctors(data || []);
  }

  async function fetchPrescriptions() {
    const { data } = await supabase.from("prescriptions").select(`*, prescription_medicines(*), doctor:doctor_id(name, specialization)`).eq("patient_id", user.id).order("date", { ascending: false });
    setPrescriptions(data || []);
  }

  async function fetchVitals() {
    const { data } = await supabase.from("vitals").select(`*, doctor:doctor_id(name)`).eq("patient_id", user.id).order("recorded_at", { ascending: false });
    setVitals(data || []);
  }

  async function fetchPendingRequests() {
    const { data } = await supabase.from("otp_requests").select(`*, doctor:doctor_id(name, specialization)`).eq("patient_id", user.id).eq("used", false).gt("expires_at", new Date().toISOString()).order("created_at", { ascending: false });
    setPendingRequests(data || []);
  }

  async function approveRequest(request) {
    await supabase.from("otp_requests").update({ patient_approved: true, used: true }).eq("id", request.id);
    alert(`OTP approved! Share this OTP with Dr. ${request.doctor?.name}: ${request.otp_code}`);
    fetchPendingRequests();
  }

  async function rejectRequest(requestId) {
    await supabase.from("otp_requests").update({ used: true }).eq("id", requestId);
    fetchPendingRequests();
  }

  return (
    <Layout user={user} onLogout={onLogout} role="patient"
      tabs={[["requests", `🔔 Requests${pendingRequests.length ? ` (${pendingRequests.length})` : ""}`], ["prescriptions", "📋 Prescriptions"], ["vitals", "📊 My Vitals"], ["doctors", "👨‍⚕️ Doctors"], ["profile", "👤 Profile"]]}
      activeTab={tab} onTabChange={setTab} subtitle={`ID: ${user.unique_id}`}
    >
      {tab === "requests" && (
        <div>
          <h2 style={headingStyle}>Doctor Access Requests</h2>
          {pendingRequests.length === 0 ? (
            <div><Empty text="No pending requests." /><p style={{ textAlign: "center", color: C.muted, fontSize: 13 }}>Jab koi doctor tumhara data access karna chahega — yahan dikhega!</p></div>
          ) : pendingRequests.map(req => (
            <div key={req.id} style={{ ...s.card, padding: 20, marginBottom: 14, borderLeft: `4px solid ${C.warning}` }}>
              <div style={{ fontWeight: 700, fontSize: 16, marginBottom: 4 }}>👨‍⚕️ Dr. {req.doctor?.name}</div>
              <div style={{ color: C.muted, fontSize: 13, marginBottom: 4 }}>{req.doctor?.specialization}</div>
              <div style={{ color: C.muted, fontSize: 12 }}>Request time: {new Date(req.created_at).toLocaleTimeString()}</div>
              <div style={{ marginTop: 8, padding: "6px 12px", background: C.warningLight, borderRadius: 8, fontSize: 13, color: C.warning, fontWeight: 600 }}>⚠️ Ye doctor tumhari saari prescriptions dekhna chahta hai</div>
              <div style={{ display: "flex", gap: 10, marginTop: 16 }}>
                <button onClick={() => rejectRequest(req.id)} style={{ ...s.btn("danger"), flex: 1 }}>✕ Reject</button>
                <button onClick={() => approveRequest(req)} style={{ ...s.btn("accent"), flex: 2 }}>✓ Approve & Show OTP</button>
              </div>
            </div>
          ))}
        </div>
      )}

      {tab === "prescriptions" && (
        <div>
          <h2 style={headingStyle}>My Prescriptions ({prescriptions.length})</h2>
          {prescriptions.length === 0 ? <Empty text="No prescriptions yet." /> :
            prescriptions.map(rx => <RxCard key={rx.id} rx={rx} showDoctor doctor={rx.doctor} />)}
        </div>
      )}

      {tab === "vitals" && (
        <div>
          <h2 style={headingStyle}>My Vitals History</h2>
          {vitals.length === 0 ? (
            <div>
              <Empty text="No vitals recorded yet." />
              <p style={{ textAlign: "center", color: C.muted, fontSize: 13 }}>Doctor prescription likhte waqt tumhare vitals record karega!</p>
            </div>
          ) : (
            <div>
              {/* Summary Cards */}
              {vitals.length > 0 && (
                <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 12, marginBottom: 24 }}>
                  {vitals[0].bp_systolic && <VitalSummaryCard icon="🫀" label="Latest BP" value={`${vitals[0].bp_systolic}/${vitals[0].bp_diastolic}`} unit="mmHg" color={C.danger} />}
                  {vitals[0].sugar_fasting && <VitalSummaryCard icon="🍬" label="Sugar (F)" value={vitals[0].sugar_fasting} unit="mg/dL" color={C.warning} />}
                  {vitals[0].cholesterol && <VitalSummaryCard icon="🧪" label="Cholesterol" value={vitals[0].cholesterol} unit="mg/dL" color={C.purple} />}
                  {vitals[0].weight && <VitalSummaryCard icon="⚖️" label="Weight" value={vitals[0].weight} unit="kg" color={C.primary} />}
                </div>
              )}

              {/* Vitals History */}
              {vitals.map((v, i) => (
                <div key={v.id} style={{ ...s.card, padding: 16, marginBottom: 12 }}>
                  <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 12 }}>
                    <div style={{ fontWeight: 600, color: C.primary }}>📅 {new Date(v.recorded_at).toLocaleDateString()}</div>
                    <div style={{ color: C.muted, fontSize: 12 }}>Dr. {v.doctor?.name}</div>
                  </div>
                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}>
                    {v.bp_systolic && <VitalItem icon="🫀" label="BP" value={`${v.bp_systolic}/${v.bp_diastolic} mmHg`} />}
                    {v.sugar_fasting && <VitalItem icon="🍬" label="Sugar (F)" value={`${v.sugar_fasting} mg/dL`} />}
                    {v.sugar_pp && <VitalItem icon="🍬" label="Sugar (PP)" value={`${v.sugar_pp} mg/dL`} />}
                    {v.cholesterol && <VitalItem icon="🧪" label="Cholesterol" value={`${v.cholesterol} mg/dL`} />}
                    {v.weight && <VitalItem icon="⚖️" label="Weight" value={`${v.weight} kg`} />}
                    {v.temperature && <VitalItem icon="🌡️" label="Temp" value={`${v.temperature} °F`} />}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {tab === "doctors" && (
        <div>
          <h2 style={headingStyle}>Find a Doctor</h2>
          <div style={{ marginBottom: 20 }}>
            <input
              value={searchSpec}
              onChange={e => setSearchSpec(e.target.value)}
              placeholder="Search by name or specialization..."
              style={{ ...s.input }}
            />
          </div>
          {/* Specialty groups */}
          {(() => {
            const filtered = doctors.filter(d =>
              d.name.toLowerCase().includes(searchSpec.toLowerCase()) ||
              (d.specialization || "").toLowerCase().includes(searchSpec.toLowerCase())
            );
            if (filtered.length === 0) return <Empty text="No doctors found." />;
            
            // Group by specialization
            const groups = {};
            filtered.forEach(d => {
              const spec = d.specialization || "General";
              if (!groups[spec]) groups[spec] = [];
              groups[spec].push(d);
            });

            return Object.entries(groups).map(([spec, docs]) => (
              <div key={spec} style={{ marginBottom: 24 }}>
                <h3 style={{ fontSize: 13, color: C.muted, letterSpacing: 1, textTransform: "uppercase", marginBottom: 12 }}>
                  🩺 {spec}
                </h3>
                {docs.map(d => (
                  <div key={d.id} style={{ ...s.card, padding: 16, marginBottom: 10, display: "flex", alignItems: "center", gap: 14 }}>
                    <div style={{ width: 48, height: 48, borderRadius: 12, background: C.primaryLight, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22, flexShrink: 0 }}>👨‍⚕️</div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontWeight: 700, fontSize: 15 }}>Dr. {d.name}</div>
                      <div style={{ color: C.muted, fontSize: 13 }}>{d.specialization || "General Physician"}</div>
                      <div style={{ marginTop: 4 }}><span style={s.badge(C.accent)}>Available on MediConnect</span></div>
                    </div>
                    <div style={{ fontSize: 12, color: C.primary, fontWeight: 600 }}>ID: {d.unique_id}</div>
                  </div>
                ))}
              </div>
            ));
          })()}
        </div>
      )}

      {tab === "profile" && (
        <div>
          <h2 style={headingStyle}>My Profile</h2>
          <div style={{ ...s.card, padding: 24 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 16, marginBottom: 20 }}>
              <div style={{ width: 64, height: 64, borderRadius: 16, background: C.primaryLight, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 28 }}>🧑</div>
              <div><div style={{ fontWeight: 700, fontSize: 20 }}>{user.name}</div><div style={{ color: C.muted, fontSize: 13 }}>{user.email}</div></div>
            </div>
            {[["Unique ID", user.unique_id], ["Age", user.age], ["Blood Group", user.blood_group]].map(([k, v]) => (
              <div key={k} style={{ display: "flex", justifyContent: "space-between", padding: "10px 0", borderBottom: `1px solid ${C.border}` }}>
                <span style={{ color: C.muted, fontSize: 13 }}>{k}</span><span style={{ fontWeight: 600 }}>{v || "—"}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </Layout>
  );
}

function VitalSummaryCard({ icon, label, value, unit, color }) {
  return (
    <div style={{ ...s.card, padding: 14, textAlign: "center", borderTop: `3px solid ${color}` }}>
      <div style={{ fontSize: 24, marginBottom: 6 }}>{icon}</div>
      <div style={{ fontSize: 18, fontWeight: 800, color }}>{value}</div>
      <div style={{ fontSize: 10, color: C.muted, marginTop: 2 }}>{unit}</div>
      <div style={{ fontSize: 11, color: C.muted, marginTop: 2 }}>{label}</div>
    </div>
  );
}

function VitalItem({ icon, label, value }) {
  return (
    <div style={{ padding: "8px 12px", background: C.bg, borderRadius: 8, fontSize: 13 }}>
      <span style={{ color: C.muted }}>{icon} {label}: </span>
      <strong>{value}</strong>
    </div>
  );
}

// ─── MEDICAL STORE DASHBOARD ──────────────────────────────────────────────────
function MedicalStoreDashboard({ user, onLogout }) {
  return (
    <Layout user={user} onLogout={onLogout} role="medical_store"
      tabs={[["orders", "📦 Orders"], ["profile", "🏪 Profile"]]}
      activeTab="orders" onTabChange={() => {}} subtitle={user.store_name}
    >
      <div>
        <h2 style={headingStyle}>Medical Store Dashboard</h2>
        <div style={{ ...s.card, padding: 24, textAlign: "center" }}>
          <div style={{ fontSize: 48, marginBottom: 12 }}>🏪</div>
          <div style={{ fontWeight: 700, fontSize: 18, marginBottom: 8 }}>{user.store_name || user.name}</div>
          <div style={{ color: C.muted, fontSize: 13, marginBottom: 4 }}>{user.address}</div>
          <div style={{ color: C.muted, fontSize: 13 }}>License: {user.license_no}</div>
          <div style={{ marginTop: 16, padding: "10px 20px", background: C.warningLight, borderRadius: 10, color: C.warning, fontSize: 13, fontWeight: 600 }}>
            🚧 Prescription orders feature coming soon!
          </div>
        </div>
      </div>
    </Layout>
  );
}

// ─── TEST LAB DASHBOARD ───────────────────────────────────────────────────────
function TestLabDashboard({ user, onLogout }) {
  return (
    <Layout user={user} onLogout={onLogout} role="test_lab"
      tabs={[["bookings", "🔬 Bookings"], ["profile", "🏥 Profile"]]}
      activeTab="bookings" onTabChange={() => {}} subtitle={user.store_name}
    >
      <div>
        <h2 style={headingStyle}>Test Lab Dashboard</h2>
        <div style={{ ...s.card, padding: 24, textAlign: "center" }}>
          <div style={{ fontSize: 48, marginBottom: 12 }}>🔬</div>
          <div style={{ fontWeight: 700, fontSize: 18, marginBottom: 8 }}>{user.store_name || user.name}</div>
          <div style={{ color: C.muted, fontSize: 13, marginBottom: 4 }}>{user.address}</div>
          <div style={{ color: C.muted, fontSize: 13 }}>License: {user.license_no}</div>
          <div style={{ marginTop: 16, padding: "10px 20px", background: C.purpleLight, borderRadius: 10, color: C.purple, fontSize: 13, fontWeight: 600 }}>
            🚧 Test booking feature coming soon!
          </div>
        </div>
      </div>
    </Layout>
  );
}

// ─── PRESCRIPTION FORM ────────────────────────────────────────────────────────
function PrescriptionForm({ patient, onSave, onCancel }) {
  const [diagnosis, setDiagnosis] = useState("");
  const [notes, setNotes] = useState("");
  const [medicines, setMedicines] = useState([{ name: "", dosage: "", frequency: "", duration: "" }]);
  const [vitals, setVitals] = useState({ bp_systolic: "", bp_diastolic: "", sugar_fasting: "", sugar_pp: "", cholesterol: "", weight: "", temperature: "" });
  const [showVitals, setShowVitals] = useState(false);
  const [medSuggestions, setMedSuggestions] = useState({});

  async function searchMedicines(query, index) {
    if (!query || query.length < 2) { setMedSuggestions(p => ({ ...p, [index]: [] })); return; }
    const { data } = await supabase.from("medicines").select("name, category").ilike("name", `%${query}%`).limit(6);
    setMedSuggestions(p => ({ ...p, [index]: data || [] }));
  }

  return (
    <div>
      <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}>
        <button onClick={onCancel} style={{ ...s.btn("ghost"), padding: "8px 12px" }}>← Back</button>
        <h2 style={{ ...headingStyle, margin: 0 }}>Write Prescription</h2>
      </div>
      <div style={{ ...s.card, padding: 16, marginBottom: 20, background: C.primaryLight }}>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 4 }}>PATIENT</div>
        <div style={{ fontWeight: 700, fontSize: 16 }}>{patient.name}</div>
        <div style={{ color: C.muted, fontSize: 13 }}>{patient.unique_id} • Age {patient.age} • {patient.blood_group}</div>
      </div>

      <Field label="Diagnosis" value={diagnosis} onChange={setDiagnosis} placeholder="e.g. Hypertension" />

      {/* VITALS SECTION */}
      <div style={{ marginBottom: 20 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
          <label style={s.label}>📊 Vitals (Optional)</label>
          <button onClick={() => setShowVitals(v => !v)} style={{ ...s.btn("ghost"), padding: "6px 14px", fontSize: 12, border: `1px solid ${C.border}` }}>
            {showVitals ? "Hide Vitals" : "Add Vitals"}
          </button>
        </div>
        {showVitals && (
          <div style={{ ...s.card, padding: 16, background: "#F8FDFF", border: `1px solid ${C.primary}22` }}>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
              <Field label="BP Systolic (mmHg)" value={vitals.bp_systolic} onChange={v => setVitals(p => ({ ...p, bp_systolic: v }))} placeholder="120" type="number" noMargin />
              <Field label="BP Diastolic (mmHg)" value={vitals.bp_diastolic} onChange={v => setVitals(p => ({ ...p, bp_diastolic: v }))} placeholder="80" type="number" noMargin />
              <Field label="Sugar Fasting (mg/dL)" value={vitals.sugar_fasting} onChange={v => setVitals(p => ({ ...p, sugar_fasting: v }))} placeholder="100" type="number" noMargin />
              <Field label="Sugar PP (mg/dL)" value={vitals.sugar_pp} onChange={v => setVitals(p => ({ ...p, sugar_pp: v }))} placeholder="140" type="number" noMargin />
              <Field label="Cholesterol (mg/dL)" value={vitals.cholesterol} onChange={v => setVitals(p => ({ ...p, cholesterol: v }))} placeholder="200" type="number" noMargin />
              <Field label="Weight (kg)" value={vitals.weight} onChange={v => setVitals(p => ({ ...p, weight: v }))} placeholder="70" type="number" noMargin />
            </div>
            <div style={{ marginTop: 10 }}>
              <Field label="Temperature (°F)" value={vitals.temperature} onChange={v => setVitals(p => ({ ...p, temperature: v }))} placeholder="98.6" type="number" noMargin />
            </div>
          </div>
        )}
      </div>

      <div style={{ marginBottom: 20 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
          <label style={s.label}>Medicines</label>
          <button onClick={() => setMedicines(p => [...p, { name: "", dosage: "", frequency: "", duration: "" }])} style={{ ...s.btn("accent"), padding: "6px 14px", fontSize: 12 }}>+ Add</button>
        </div>
        {medicines.map((med, i) => (
          <div key={i} style={{ ...s.card, padding: 14, marginBottom: 10 }}>
            <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 10 }}>
              <span style={{ fontWeight: 600, color: C.primary, fontSize: 13 }}>Medicine {i + 1}</span>
              {medicines.length > 1 && <button onClick={() => setMedicines(p => p.filter((_, idx) => idx !== i))} style={{ background: "none", border: "none", color: C.danger, cursor: "pointer", fontSize: 16 }}>✕</button>}
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
              <div style={{ position: "relative" }}>
                <label style={s.label}>Name</label>
                <input
                  value={med.name}
                  onChange={e => { const v = e.target.value; setMedicines(p => p.map((m, idx) => idx === i ? { ...m, name: v } : m)); searchMedicines(v, i); }}
                  placeholder="Medicine name"
                  style={{ ...s.input, marginBottom: 0 }}
                />
                {medSuggestions[i] && medSuggestions[i].length > 0 && (
                  <div style={{ position: "absolute", top: "100%", left: 0, right: 0, background: "#fff", border: `1px solid ${C.border}`, borderRadius: 8, zIndex: 100, boxShadow: C.shadow }}>
                    {medSuggestions[i].map((sug, j) => (
                      <div key={j} onClick={() => { setMedicines(p => p.map((m, idx) => idx === i ? { ...m, name: sug.name } : m)); setMedSuggestions(p => ({ ...p, [i]: [] })); }} style={{ padding: "8px 12px", cursor: "pointer", fontSize: 13, borderBottom: `1px solid ${C.border}`, display: "flex", justifyContent: "space-between" }}>
                        <span>💊 {sug.name}</span>
                        <span style={{ color: C.muted, fontSize: 11 }}>{sug.category}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
              <Field label="Dosage" value={med.dosage} onChange={v => setMedicines(p => p.map((m, idx) => idx === i ? { ...m, dosage: v } : m))} placeholder="500mg" noMargin />
              <Field label="Frequency" value={med.frequency} onChange={v => setMedicines(p => p.map((m, idx) => idx === i ? { ...m, frequency: v } : m))} placeholder="2x daily" noMargin />
              <Field label="Duration" value={med.duration} onChange={v => setMedicines(p => p.map((m, idx) => idx === i ? { ...m, duration: v } : m))} placeholder="7 days" noMargin />
            </div>
          </div>
        ))}
      </div>
      <Field label="Notes (optional)" value={notes} onChange={setNotes} placeholder="Additional advice..." textarea />
      <div style={{ display: "flex", gap: 10 }}>
        <button onClick={onCancel} style={{ ...s.btn("ghost"), flex: 1 }}>Cancel</button>
        <button onClick={() => {
          if (!diagnosis.trim()) return alert("Please enter diagnosis.");
          if (medicines.some(m => !m.name.trim())) return alert("Fill all medicine names.");
          onSave({ diagnosis, notes, medicines, vitals: showVitals ? vitals : null });
        }} style={{ ...s.btn("primary"), flex: 2 }}>💾 Save Prescription</button>
      </div>
    </div>
  );
}

// ─── RX CARD ─────────────────────────────────────────────────────────────────
function RxCard({ rx, doctor, patient, showDoctor, showPatient }) {
  const [open, setOpen] = useState(false);
  const medicines = rx.prescription_medicines || [];
  return (
    <div style={{ ...s.card, marginBottom: 12, overflow: "hidden" }}>
      <div onClick={() => setOpen(o => !o)} style={{ padding: "14px 18px", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div>
          <div style={{ fontWeight: 700, fontSize: 15 }}>{rx.diagnosis}</div>
          <div style={{ color: C.muted, fontSize: 12, marginTop: 2 }}>{showDoctor && doctor && `Dr. ${doctor.name} • `}{showPatient && patient && `${patient.name} • `}{rx.date}</div>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <span style={s.badge(C.primary)}>{medicines.length} med{medicines.length !== 1 ? "s" : ""}</span>
          <span style={{ color: C.muted, fontSize: 18 }}>{open ? "▲" : "▼"}</span>
          <button onClick={e => { e.stopPropagation(); downloadPDF(rx, doctor || rx.doctor, patient || rx.patient); }} style={{ background: C.primary, color: "#fff", border: "none", borderRadius: 8, padding: "4px 10px", fontSize: 11, cursor: "pointer", marginLeft: 8, fontFamily: "inherit" }}>📄 PDF</button>
        </div>
      </div>
      {open && (
        <div style={{ borderTop: `1px solid ${C.border}`, padding: "14px 18px", background: "#FAFCFF" }}>
          {showDoctor && doctor && <div style={{ marginBottom: 12, padding: 10, background: C.primaryLight, borderRadius: 8 }}><span style={{ fontSize: 12, color: C.muted }}>Prescribed by: </span><strong>{doctor.name}</strong><span style={{ color: C.muted, fontSize: 12 }}> ({doctor.specialization})</span></div>}
          {showPatient && patient && <div style={{ marginBottom: 12, padding: 10, background: C.accentLight, borderRadius: 8 }}><span style={{ fontSize: 12, color: C.muted }}>Patient: </span><strong>{patient.name}</strong><span style={{ color: C.muted, fontSize: 12 }}> ({patient.unique_id})</span></div>}
          {medicines.map((m, i) => (
            <div key={i} style={{ display: "grid", gridTemplateColumns: "2fr 1fr 1fr 1fr", gap: 8, padding: "8px 0", borderBottom: `1px solid ${C.border}`, fontSize: 13 }}>
              <span style={{ fontWeight: 600 }}>💊 {m.medicine_name}</span>
              <span style={{ color: C.muted }}>{m.dosage}</span>
              <span style={{ color: C.muted }}>{m.frequency}</span>
              <span style={{ color: C.muted }}>{m.duration}</span>
            </div>
          ))}
          {rx.notes && <div style={{ marginTop: 10, padding: 10, background: "#FFF9E6", borderRadius: 8, fontSize: 13, color: "#7A6030" }}>📝 {rx.notes}</div>}
        </div>
      )}
    </div>
  );
}

// ─── SHARED COMPONENTS ────────────────────────────────────────────────────────
function Layout({ user, onLogout, role, tabs, activeTab, onTabChange, subtitle, children }) {
  const roleColors = { admin: "#E74C3C", doctor: C.primary, patient: C.accent, medical_store: C.warning, test_lab: C.purple };
  const roleLabels = { admin: "ADMIN", doctor: "DOCTOR", patient: "PATIENT", medical_store: "MED STORE", test_lab: "TEST LAB" };
  const roleColor = roleColors[role] || C.primary;
  return (
    <div style={s.page}>
      <div style={{ background: "#fff", borderBottom: `3px solid ${roleColor}`, boxShadow: "0 2px 12px rgba(0,0,0,0.06)", position: "sticky", top: 0, zIndex: 100 }}>
        <div style={{ maxWidth: 720, margin: "0 auto", padding: "14px 20px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <span style={{ fontSize: 26 }}>🏥</span>
            <div><div style={{ fontWeight: 800, fontSize: 18, color: C.primary }}>MediConnect</div><div style={{ fontSize: 11, color: C.muted }}>{user.name}{subtitle ? ` • ${subtitle}` : ""}</div></div>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <span style={s.badge(roleColor)}>{roleLabels[role] || role.toUpperCase()}</span>
            <button onClick={onLogout} style={{ ...s.btn("ghost"), padding: "6px 12px", fontSize: 12 }}>Logout</button>
          </div>
        </div>
        <div style={{ maxWidth: 720, margin: "0 auto", padding: "0 20px", display: "flex", overflowX: "auto" }}>
          {tabs.map(([t, label]) => (
            <button key={t} onClick={() => onTabChange(t)} style={{ padding: "10px 18px", border: "none", borderBottom: `3px solid ${activeTab === t ? roleColor : "transparent"}`, background: "transparent", fontFamily: "inherit", fontSize: 13, cursor: "pointer", color: activeTab === t ? roleColor : C.muted, fontWeight: activeTab === t ? 700 : 400, marginBottom: -3, whiteSpace: "nowrap" }}>{label}</button>
          ))}
        </div>
      </div>
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "24px 20px" }}>{children}</div>
    </div>
  );
}

function StatCard({ icon, label, value, color }) {
  return <div style={{ ...s.card, padding: 20, textAlign: "center", borderTop: `4px solid ${color}` }}><div style={{ fontSize: 32, marginBottom: 8 }}>{icon}</div><div style={{ fontSize: 32, fontWeight: 800, color }}>{value}</div><div style={{ fontSize: 12, color: C.muted, marginTop: 4 }}>{label}</div></div>;
}

function PendingCard({ user, onApprove, onReject }) {
  const roleColors = { doctor: C.primary, patient: C.accent, medical_store: C.warning, test_lab: C.purple };
  const roleColor = roleColors[user.role] || C.muted;
  return (
    <div style={{ ...s.card, padding: 16, marginBottom: 10, display: "flex", justifyContent: "space-between", alignItems: "center", borderLeft: `4px solid ${C.danger}` }}>
      <div><div style={{ fontWeight: 700 }}>{user.name} <span style={s.badge(roleColor)}>{user.role}</span></div><div style={{ color: C.muted, fontSize: 12 }}>{user.email}{user.specialization ? ` • ${user.specialization}` : ""}{user.store_name ? ` • ${user.store_name}` : ""}</div></div>
      <div style={{ display: "flex", gap: 8 }}><button onClick={onApprove} style={s.btn("accent")}>✓ Approve</button><button onClick={onReject} style={s.btn("danger")}>✕ Reject</button></div>
    </div>
  );
}

function UserCard({ user, extra, onDelete }) {
  return (
    <div style={{ ...s.card, padding: 16, marginBottom: 10, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
      <div><div style={{ fontWeight: 700 }}>{user.name}</div><div style={{ color: C.muted, fontSize: 12 }}>{user.unique_id} • {extra} • {user.email}</div><div style={{ marginTop: 4 }}><span style={s.badge(user.approved ? C.accent : C.danger)}>{user.approved ? "Active" : "Pending"}</span></div></div>
      <button onClick={onDelete} style={{ background: "none", border: "none", color: `${C.danger}66`, cursor: "pointer", fontSize: 20, padding: 4 }}>🗑</button>
    </div>
  );
}

function Field({ label, value, onChange, placeholder, type = "text", textarea, noMargin }) {
  return (
    <div style={{ marginBottom: noMargin ? 0 : 14 }}>
      <label style={s.label}>{label}</label>
      {textarea ? <textarea value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} style={{ ...s.input, height: 80, resize: "vertical", marginBottom: 0 }} /> : <input type={type} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} style={{ ...s.input, marginBottom: 0 }} />}
    </div>
  );
}

function Empty({ text }) {
  return <div style={{ textAlign: "center", color: C.muted, padding: "48px 20px", fontSize: 15 }}>🗂 {text}</div>;
}

const headingStyle = { fontSize: 20, fontWeight: 800, marginBottom: 18, color: C.text };
